### ISSUE TITLE
Is it possible for you to not include the changelog in your rust-analyzer updates here (or delinkify it)? 

### ISSUE THREAD

**Issue by Veykril** [philips-software/amp-devcontainer#477]
Is it possible for you to not include the changelog here (or delinkify it)? This completely pollutes our pull request views in rust-analyzer
![image](https://github.com/philips-software/amp-devcontainer/assets/3757771/9c2d303d-b01d-4d97-919c-e9ad28027c21)

_Originally posted by @Veykril in https://github.com/philips-software/amp-devcontainer/issues/456#issuecomment-2185898600_

**Comment by rjaegers** [comment]
@Veykril I'll follow the recommendation posted [here](https://github.com/orgs/community/discussions/23123#discussioncomment-3239240) to prevent the backlink creation.

Please let me know if there are any remaining issues or if there is regression regarding the solution.

My apologies for the spam!

**Comment by Veykril** [comment]
Thank you!
